In [1]:
# Week 3 – NumPy and Pandas
# ASSIGNMENT 1: NumPy Array Explorer
# Objective: Demonstrate NumPy array creation methods and basic operations.

# Instructions:
# 1. Import NumPy as np.
# 2. Create the following arrays:
#    - Array A: 1D array from list [2,4,6,8,10,12,14,16,18,20]
#    - Array B: 3x3 array of zeros
#    - Array C: 5 random integers between 1 and 100
#    - Array D: 10 evenly spaced numbers between 0 and 5 using np.linspace()

# 3. For Array A print:
#    - Shape
#    - Data type
#    - Size
#    - Number of dimensions

# 4. Perform operations on Array A:
#    - Reshape to 2x5
#    - Find max value and index
#    - Find min value and index

# 5. Create Array E = [[1,2,3],[4,5,6],[7,8,9]]
#    Print element at row 1 column 2.

# 1. Import NumPy
import numpy as np

# 2. Create Arrays

# Array A
A = np.array([2,4,6,8,10,12,14,16,18,20])

# Array B (3x3 zeros)
B = np.zeros((3,3))

# Array C (5 random integers between 1 and 100)
C = np.random.randint(1, 101, 5)

# Array D (10 evenly spaced numbers between 0 and 5)
D = np.linspace(0, 5, 10)

# Print arrays
print("Array A:", A)
print("Array B:\n", B)
print("Array C:", C)
print("Array D:", D)


# 3. Properties of Array A
print("\n--- Array A Properties ---")
print("Shape:", A.shape)
print("Data Type:", A.dtype)
print("Size:", A.size)
print("Dimensions:", A.ndim)


# 4. Operations on Array A

# Reshape to 2x5
A_reshaped = A.reshape(2,5)
print("\nReshaped A (2x5):\n", A_reshaped)

# Max value and index
print("Max value:", A.max())
print("Index of max value:", A.argmax())

# Min value and index
print("Min value:", A.min())
print("Index of min value:", A.argmin())


# 5. Array E
E = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Element at row 1 column 2
print("\nElement at row 1 column 2:", E[1,2])


Array A: [ 2  4  6  8 10 12 14 16 18 20]
Array B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array C: [36 60 94 17 64]
Array D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

--- Array A Properties ---
Shape: (10,)
Data Type: int64
Size: 10
Dimensions: 1

Reshaped A (2x5):
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max value: 20
Index of max value: 9
Min value: 2
Index of min value: 0

Element at row 1 column 2: 6


In [2]:
# ASSIGNMENT 2: NumPy Array Math Wizard
# Objective: Demonstrate broadcasting and universal functions.
# Instructions:
# 1. Import NumPy as np.
# 2. Create:
#    arr1 = [[1,2,3],[4,5,6]]
#    arr2 = [10,20,30]
# 3. Perform:
#    - Addition
#    - Subtraction
#    - Multiplication
#    - Division
# 4. Explain broadcasting in a comment.
# 5. Create arr3 = [1,4,9,16,25] and apply:
#    - np.sqrt()
#    - np.exp()
#    - np.sin()
# 6. Create arr4 = [[5,12,3],[8,2,7]] and demonstrate:
#    - Sum of all elements
#    - Max in each column
#    - Min in each row
# 7. Convert arr1 to float using type casting.

# 1. Import NumPy
import numpy as np

# 2. Create arrays
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])

print("arr1:\n", arr1)
print("arr2:", arr2)

# 3. Operations (Broadcasting will happen here)

print("\n--- Addition ---")
print(arr1 + arr2)

print("\n--- Subtraction ---")
print(arr1 - arr2)

print("\n--- Multiplication ---")
print(arr1 * arr2)

print("\n--- Division ---")
print(arr1 / arr2)

# 4. Broadcasting Explanation
# Broadcasting means NumPy automatically adjusts the shape of arrays so they can perform operations together.
# Example: arr2 (1D) is applied to each row of arr1 (2D)

# 5. Universal Functions
arr3 = np.array([1,4,9,16,25])

print("\n--- Universal Functions ---")
print("Square Root:", np.sqrt(arr3))
print("Exponential:", np.exp(arr3))
print("Sine:", np.sin(arr3))

# 6. Array operations
arr4 = np.array([[5,12,3],[8,2,7]])

print("\narr4:\n", arr4)

# Sum of all elements
print("Total Sum:", np.sum(arr4))

# Max in each column
print("Max in each column:", np.max(arr4, axis=0))

# Min in each row
print("Min in each row:", np.min(arr4, axis=1))

# 7. Type Casting
arr1_float = arr1.astype(float)
print("\narr1 converted to float:\n", arr1_float)


arr1:
 [[1 2 3]
 [4 5 6]]
arr2: [10 20 30]

--- Addition ---
[[11 22 33]
 [14 25 36]]

--- Subtraction ---
[[ -9 -18 -27]
 [ -6 -15 -24]]

--- Multiplication ---
[[ 10  40  90]
 [ 40 100 180]]

--- Division ---
[[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]

--- Universal Functions ---
Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

arr4:
 [[ 5 12  3]
 [ 8  2  7]]
Total Sum: 37
Max in each column: [ 8 12  7]
Min in each row: [3 2]

arr1 converted to float:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
# ASSIGNMENT 3: Pandas DataFrame Detective
# Objective: Perform basic exploratory data analysis using Pandas.
# Instructions:
# 1. Import pandas as pd and numpy as np.
# 2. Create dictionary:
# data = {
# 'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
# 'Age': [25,30,np.nan,35,28,np.nan],
# 'Score': [85,92,78,np.nan,88,95],
# 'Grade': ['A','A','B','C','B','A']
# }
# 3. Create DataFrame df.
# 4. Perform:
#    - df.head(3)
#    - df.shape
#    - df.columns
#    - df.dtypes
# 5. Missing data:
#    - df.isnull()
#    - Fill Age with mean
#    - Drop rows with missing Score
# 6. Selection:
#    - Select Name and Score
#    - Select rows where Score > 85
#    - Set Name as index
# 7. Operations:
#    - Unique grades
#    - Grade counts
#    - Sort by Score descending

# 1. Import libraries
import pandas as pd
import numpy as np

# 2. Create dictionary
data = {
    'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
    'Age': [25,30,np.nan,35,28,np.nan],
    'Score': [85,92,78,np.nan,88,95],
    'Grade': ['A','A','B','C','B','A']
}

# 3. Create DataFrame
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# 4. Basic Info
print("\n--- Basic Info ---")
print("Head (first 3 rows):\n", df.head(3))
print("Shape:", df.shape)
print("Columns:", df.columns)
print("Data Types:\n", df.dtypes)

# 5. Missing Data
print("\n--- Missing Data ---")
# Check missing values
print(df.isnull())
# Fill Age with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())
print("\nAfter filling Age:\n", df)
# Drop rows with missing Score
df = df.dropna(subset=['Score'])
print("\nAfter dropping missing Score:\n", df)


# 6. Selection
print("\n--- Selection ---")
# Select Name and Score
print(df[['Name','Score']])
# Rows where Score > 85
print("\nScore > 85:\n", df[df['Score'] > 85])
# Set Name as index
df = df.set_index('Name')
print("\nAfter setting Name as index:\n", df)


# 7. Operations
print("\n--- Operations ---")
# Unique grades
print("Unique Grades:", df['Grade'].unique())
# Grade counts
print("Grade Counts:\n", df['Grade'].value_counts())
# Sort by Score descending
print("\nSorted by Score:\n", df.sort_values(by='Score', ascending=False))


DataFrame:
       Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank   NaN   95.0     A

--- Basic Info ---
Head (first 3 rows):
       Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
Shape: (6, 4)
Columns: Index(['Name', 'Age', 'Score', 'Grade'], dtype='object')
Data Types:
 Name      object
Age      float64
Score    float64
Grade     object
dtype: object

--- Missing Data ---
    Name    Age  Score  Grade
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3  False  False   True  False
4  False  False  False  False
5  False   True  False  False

After filling Age:
       Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Fra